import 'package:flutter_test/flutter_test.dart';
import 'package:splito_flutter/features/analytics/domain/entities/group_analytics.dart';
import 'package:splito_flutter/features/analytics/domain/entities/member_contribution.dart';
import 'package:splito_flutter/features/analytics/domain/entities/monthly_spending.dart';
import 'package:splito_flutter/features/analytics/domain/services/export_service.dart';
import 'package:splito_flutter/features/expenses/domain/entities/expense.dart';
import 'package:splito_flutter/features/expenses/domain/entities/expense_participant.dart';
import 'package:splito_flutter/features/expenses/domain/entities/split_type.dart';
import 'package:splito_flutter/features/settlements/domain/entities/settlement.dart';

final tParticipant1 = ExpenseParticipant(
  userId: 'user-1',
  name: 'Mandeep',
  owedAmount: 1000.0,
);
final tParticipant2 = ExpenseParticipant(
  userId: 'user-2',
  name: 'Rahul',
  owedAmount: 2000.0,
);

final tExpense1 = Expense(
  id: 'exp-1',
  groupId: 'group-1',
  paidByUserId: 'user-1',
  paidByName: 'Mandeep',
  title: 'Dinner',
  totalAmount: 3000.0,
  currency: 'INR',
  splitType: SplitType.equal,
  status: 'ACTIVE',
  createdAt: DateTime(2026, 1, 15),
  participants: [tParticipant1, tParticipant2],
);

final tExpense2 = Expense(
  id: 'exp-2',
  groupId: 'group-1',
  paidByUserId: 'user-2',
  paidByName: 'Rahul',
  title: 'Hotel',
  totalAmount: 6000.0,
  currency: 'INR',
  splitType: SplitType.exact,
  status: 'ACTIVE',
  createdAt: DateTime(2026, 2, 10),
  participants: [tParticipant1, tParticipant2],
);

final tReversedExpense = Expense(
  id: 'exp-3',
  groupId: 'group-1',
  paidByUserId: 'user-1',
  paidByName: 'Mandeep',
  title: 'Cancelled',
  totalAmount: 500.0,
  currency: 'INR',
  splitType: SplitType.equal,
  status: 'REVERSED',
  createdAt: DateTime(2026, 1, 20),
  participants: const [],
);

final tSettlement = Settlement(
  id: 'set-1',
  groupId: 'group-1',
  fromUserId: 'user-2',
  fromUserName: 'Rahul',
  toUserId: 'user-1',
  toUserName: 'Mandeep',
  amount: 1000.0,
  currency: 'INR',
  status: 'COMPLETED',
  createdAt: DateTime(2026, 2, 1),
);

void main() {
  const service = ExportService();

  group('generateGroupSummary', () {
    final analytics = GroupAnalytics(
      groupId: 'group-1',
      groupName: 'Test Group',
      currency: 'INR',
      totalExpenses: 9000.0,
      totalExpenseCount: 2,
      totalSettled: 1000.0,
      averageExpenseAmount: 4500.0,
      largestExpense: 6000.0,
      largestExpenseTitle: 'Dinner',
      topSpenderName: 'Mandeep',
      settlementRate: 0.5,
      memberContributions: const [
        MemberContribution(
          userId: 'u1',
          name: 'Mandeep',
          totalPaid: 3000.0,
          totalOwed: 2000.0,
          netBalance: 1000.0,
          expenseCount: 1,
          percentageOfTotal: 0.33,
        ),
      ],
      monthlySpending: const [
        MonthlySpending(
          year: 2026,
          month: 1,
          monthLabel: 'Jan',
          totalAmount: 3000.0,
          expenseCount: 1,
          currency: 'INR',
        ),
      ],
    );

    test('contains group name', () {
      final result = service.generateGroupSummary(
        analytics: analytics,
        groupName: 'Test Group',
        currency: 'INR',
      );
      expect(result, contains('Test Group'));
    });

    test('contains total spent formatted', () {
      final result = service.generateGroupSummary(
        analytics: analytics,
        groupName: 'Test Group',
        currency: 'INR',
      );
      expect(result, contains('₹9000.00'));
    });

    test('contains member name', () {
      final result = service.generateGroupSummary(
        analytics: analytics,
        groupName: 'Test Group',
        currency: 'INR',
      );
      expect(result, contains('Mandeep'));
    });

    test('contains monthly period label', () {
      final result = service.generateGroupSummary(
        analytics: analytics,
        groupName: 'Test Group',
        currency: 'INR',
      );
      expect(result, contains('Jan 2026'));
    });

    test('ends with Splito credit', () {
      final result = service.generateGroupSummary(
        analytics: analytics,
        groupName: 'Test Group',
        currency: 'INR',
      );
      expect(result, contains('Generated by Splito'));
    });

    test('INR symbol is ₹', () {
      final result = service.generateGroupSummary(
        analytics: analytics,
        groupName: 'Test Group',
        currency: 'INR',
      );
      expect(result, contains('₹'));
    });

    test('USD symbol is \$', () {
      final usdAnalytics = GroupAnalytics(
        groupId: 'group-1',
        groupName: 'G',
        currency: 'USD',
        totalExpenses: 9000.0,
        totalExpenseCount: 2,
        totalSettled: 1000.0,
        averageExpenseAmount: 4500.0,
        largestExpense: 6000.0,
        largestExpenseTitle: 'Dinner',
        topSpenderName: 'Mandeep',
        settlementRate: 0.5,
        memberContributions: const [
          MemberContribution(
            userId: 'u1',
            name: 'Mandeep',
            totalPaid: 3000.0,
            totalOwed: 2000.0,
            netBalance: 1000.0,
            expenseCount: 1,
            percentageOfTotal: 0.33,
          ),
        ],
        monthlySpending: const [
          MonthlySpending(
            year: 2026,
            month: 1,
            monthLabel: 'Jan',
            totalAmount: 3000.0,
            expenseCount: 1,
            currency: 'USD',
          ),
        ],
      );

      final usdResult = service.generateGroupSummary(
        analytics: usdAnalytics,
        groupName: 'G',
        currency: 'USD',
      );
      expect(usdResult, contains('\$'));
    });
  });
}
