import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:splito_flutter/features/analytics/domain/entities/group_analytics.dart';

/// Pure Dart service to format and export group analytics data to text.
class ExportService {
  /// Creates a const [ExportService].
  const ExportService();

  /// Generates a plain text summary report from computed group analytics.
  String generateGroupSummary({
    required GroupAnalytics analytics,
    required String groupName,
    required String currency,
  }) {
    final buffer = StringBuffer();
    buffer.write('📊 $groupName — Expense Summary\n');
    buffer.write('═══════════════════════\n');
    buffer.write('\n');
    buffer.write('💰 Total Spent: ${_fmt(analytics.totalExpenses, currency)}\n');
    buffer.write('📋 Expenses: ${analytics.totalExpenseCount}\n');
    buffer.write('💸 Average: ${_fmt(analytics.averageExpenseAmount, currency)}\n');
    buffer.write('\n');
    buffer.write('👥 Who Paid:\n');

    for (final c in analytics.memberContributions) {
      buffer.write('  • ${c.name}: ${_fmt(c.totalPaid, currency)}\n');
    }

    buffer.write('\n');
    buffer.write('📈 Monthly:\n');

    final monthlyList = analytics.monthlySpending;
    final displayMonthly = monthlyList.length > 6
        ? monthlyList.sublist(monthlyList.length - 6)
        : monthlyList;

    for (final m in displayMonthly) {
      buffer.write('  ${m.periodLabel}: ${_fmt(m.totalAmount, currency)}\n');
    }

    buffer.write('\n');
    buffer.write('—\nGenerated by Splito');

    return buffer.toString();
  }

  String _fmt(double amount, String currency) {
    return '${_symbol(currency)}${amount.toStringAsFixed(2)}';
  }

  String _symbol(String c) {
    switch (c) {
      case 'INR':
        return '₹';
      case 'USD':
        return '\$';
      case 'EUR':
        return '€';
      case 'GBP':
        return '£';
      default:
        return '$c ';
    }
  }

  String _fmtDate(DateTime dt) {
    return '${dt.day} ${_months[dt.month - 1]} ${dt.year}';
  }

  static const _months = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
  ];
}

/// Provider exposing the [ExportService].
final exportServiceProvider = Provider<ExportService>((ref) {
  return const ExportService();
});
